version: "3.7"
# コンテナの集まりの名前を定義
services:
    # 1つのコンテナの名前を定義
    # これ+プロジェクト(ディレクトリ)名がimage名となる
    baysian-lr:
        # ./にあるDockerfileを使う と言う意味
        build: .
        # image名をここで編集する(変える)
        image: rrrrind/baysian-lr
        # container名
        container_name: "baysian-lr"
        # コンテナを起動させ続ける
        tty: true
        # コンテナからローカルへバインドマウントする
        volumes: 
          - type: bind
            source: ./workspace/
            target: /home/workspace/
        #command: docker exec -i -t baysian-lr /bin/bash